### ISSUE TITLE
Any interest in donating to pdm-project org?

### ISSUE THREAD

**Issue by frostming** [pdm-project/pdm-build-locked#1]
Hi,

First I would like to say thank you for developing this plugin. I am willing to make some enhancements to this project instead of starting a new fork, the enhancements include:

1. Make it a backend plugin supporting both `pdm-backend` and `hatchling`
2. Switch to the new cross-platform lockfile in the coming PDM 2.11.0 release.

So I hereby ask if you are interested in migrating this project to `pdm-project` umbrella?

**Comment by sigma67** [comment]
Hey @frostming , glad you are interested in further developing this plugin. I'm fine with transferring this project as long as appropriate author/contributor credit remains.

To transfer this project to the pdm org I'd have to add you as collaborator to this project with appropriate permissions?

How would pypi publishing work then? The project is currently registered under my personal account

**Comment by frostming** [comment]
> To transfer this project to the pdm org I'd have to add you as collaborator to this project with appropriate permissions?

You can kickstart the transfer directly in the repo settings:

![image](https://github.com/sigma67/pdm-build-locked/assets/16336606/cdea2eed-8ac0-4284-b533-9f809bdee564)



> How would pypi publishing work then? The project is currently registered under my personal account

Please add me as a maintainer.

**Comment by sigma67** [comment]
I tried, but it's not possible since I don't have permissions for the target org. I invited you to this project as a collaborator. I think with Admin permissions you should be able to do it.

![image](https://github.com/sigma67/pdm-build-locked/assets/16363825/7367c7fe-b77f-4821-9ef1-7fa6a7ae0f03)

I also added you on pypi as requested.

**Comment by frostming** [comment]
@sigma67 Fine, didn't know that. I've invited you to the pdm org.

**Comment by sigma67** [comment]
Done.
