### ISSUE TITLE
Unit test assertion mismatch with documented functionality for extra-locked in optional-dependencies

### ISSUE THREAD

**Issue by tyong920** [pdm-project/pdm-build-locked#16]
## Description

I discovered a discrepancy between the assertions in [the unit tests](https://github.com/pdm-project/pdm-build-locked/blob/3d35f10d29c6056e20210c1c6a04523b74104937/tests/unit/test_backend.py#L37) and the documented functionality regarding `extra-locked` in the `optional-dependencies` [section](https://pdm-build-locked.readthedocs.io/en/stable/about/what.html).  

According to the documentation, `extra-locked` should appear in the final `optional-dependencies`. However, the unit tests do not assert this behavior correctly. Furthermore, the fact that the current unit tests pass indicates a potential issue with the actual code implementation.

## Steps to Reproduce

1. Clone the repository: `git clone https://github.com/pdm-project/pdm-build-locked.git`
2. Navigate to the unit tests: `cd pdm-build-locked/tests/unit`
3. Run the unit tests: `pytest test_backend.py`
4. Compare the test assertions with the documented functionality in [the documentation](https://pdm-build-locked.readthedocs.io/en/stable/about/what.html).

## Expected Behavior

The unit tests should assert that `extra-locked` appears in the final `optional-dependencies` as described in the documentation.

## Actual Behavior

The unit tests do not correctly assert the presence of `extra-locked` in the final `optional-dependencies`. **The fact that the current unit tests pass suggests there is a problem with the actual code implementation.**

### Unit Test Code Example

Current unit test (incorrect assertion):
<img width="816" alt="截屏2024-07-11 01 21 32" src="https://github.com/pdm-project/pdm-build-locked/assets/4580133/652df71d-7130-4f1d-ab33-e083b46aad51">
Current documentation:
<img width="749" alt="截屏2024-07-11 01 24 48" src="https://github.com/pdm-project/pdm-build-locked/assets/4580133/b21cd741-c51b-4852-bb83-a20b3005d832">

**Comment by sigma67** [comment]
Check the `pyproject.toml` of the test project `large-selected`. The point of that feature is to assert that only the groups are locked that are chosen.

Admittedly the docs on this feature are a bit meager, but it was only added yesterday.

https://pdm-build-locked.readthedocs.io/en/stable/plugins/backend.html#select-groups-to-lock

**Comment by tyong920** [comment]
Resolved. Appreciated!

**Comment by tyong920** [comment]
Resolved. Appreciated!
